version: '3.1'

services:
  webserver:
    container_name: woocommerce
    build:
      context: .
      dockerfile: Webserver.docker
    volumes:
    - data:/var/www/html
    #- ../woocommerce-transbank:/var/www/html/wp-content/plugins/woocommerce-transbank
    environment:
      WOOCOMMERCE_VERSION: 2.5.5
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DEBUG: 1
    depends_on:
    - dbserver
    ports:
    - 8082:80

  dbserver:
    container_name: mysql
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example

  wplugin:
    container_name: webpay_plugin
    build:
      context: .
      dockerfile: WordpressCli.docker
    volumes:
    - data:/var/www/html
    #- ../woocommerce-transbank:/var/www/html/wp-content/plugins/woocommerce-transbank
    depends_on:
    - webserver
    - dbserver

    command: dockerize -wait tcp://dbserver:3306 -wait http://webserver:80 -timeout 40s sh /init.sh

volumes:
  data:
